name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install
      
      - name: Create temporary directory
        run: |
          mkdir -p /tmp/cdk-output
      
      - name: Bootstrap AWS CDK
        run: npx cdk bootstrap          

      - name: Deploy to AWS
        run: |
          npx cdk synth --output /tmp/cdk-output
          npx cdk deploy --app /tmp/cdk-output
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
